pipeline {
    agent any

    stages {
    
    stage("Check the above jobs") {
      steps {
          FanInReverseBuildTrigger {
            upstreamProjects 'pipeline,test2'
            watchUpstreamRecursively true
            threshold 'STABLE'
             }
           }
      }
       
       stage(" creating project specific tar") {
         steps{
                sh "ls -lrt" 
             
         }
       } 
   }
}
